export type Product = {
  id: string;
  name: string;
  price: number;
  oldPrice?: number;
  discount?: string;
  rating: string;
  reviews: string;
  image: string;
  category: string;
  room: string;
  material: string;
  description: string;
  dimensions: string;
};

export const categories = [
  { slug: "living", name: "Ruang Tamu", image: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=600&q=85" },
  { slug: "bedroom", name: "Kamar Tidur", image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=600&q=85" },
  { slug: "dining", name: "Ruang Makan", image: "https://images.unsplash.com/photo-1604578762246-41134e37f9cc?auto=format&fit=crop&w=600&q=85" },
  { slug: "workspace", name: "Ruang Kerja", image: "https://images.unsplash.com/photo-1593642532400-2682810df593?auto=format&fit=crop&w=600&q=85" },
  { slug: "storage", name: "Penyimpanan", image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=600&q=85" },
  { slug: "lighting", name: "Pencahayaan", image: "https://images.unsplash.com/photo-1543198126-a8ad8e47fb22?auto=format&fit=crop&w=600&q=85" },
];

export const products: Product[] = [
  { id: "sofa-luna-3s", name: "Luna Sofa 3 Dudukan", price: 7499000, oldPrice: 8799000, discount: "15%", rating: "4.8", reviews: "126", image: "https://images.pexels.com/photos/6758245/pexels-photo-6758245.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Sofa", room: "living", material: "Kain linen bertekstur, rangka kayu rubberwood solid, busa high density", dimensions: "Lebar 210 cm × Dalam 92 cm × Tinggi 82 cm", description: "Sofa tiga dudukan dengan busa padat dan rangka kayu solid rendah. Sarungnya bisa dilepas untuk dibersihkan." },
  { id: "sofa-arka-l", name: "Arka Sofa Bentuk L", price: 12499000, oldPrice: 14200000, discount: "12%", rating: "4.7", reviews: "94", image: "https://images.pexels.com/photos/12273851/pexels-photo-12273851.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Sofa", room: "living", material: "Kain boucle, rangka plywood dan pinus, busa per pocket spring", dimensions: "Lebar 265 cm × Dalam 165 cm × Tinggi 84 cm", description: "Sofa sectional bentuk L besar dengan chaise di sisi kanan. Cocok untuk ruang keluarga terbuka dan nyaman diduduki lima orang." },
  { id: "sofa-nusa-2s", name: "Nusa Sofa 2 Dudukan", price: 5499000, rating: "4.6", reviews: "71", image: "https://images.pexels.com/photos/36363110/pexels-photo-36363110.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Sofa", room: "living", material: "Kain campuran katun, rangka kayu jati solid, busa medium density", dimensions: "Lebar 158 cm × Dalam 88 cm × Tinggi 80 cm", description: "Sofa dua dudukan ringkas untuk kamar kecil dan apartemen. Lengan tipis menjaga lebar di bawah satu setengah meter." },
  { id: "sofa-bima-recliner", name: "Bima Sofa Recliner 3 Dudukan", price: 15900000, rating: "4.7", reviews: "64", image: "https://images.pexels.com/photos/6480707/pexels-photo-6480707.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Sofa", room: "living", material: "Kulit sintetis, mekanisme recliner baja, rangka kayu kering oven", dimensions: "Lebar 218 cm × Dalam 98 cm × Tinggi 100 cm", description: "Sofa tiga dudukan dengan dua kursi recliner manual. Mekanisme baja dapat direbahkan penuh dan terkunci di tiga posisi." },
  { id: "sofa-sekar-daybed", name: "Sekar Sofa Bed", price: 9250000, oldPrice: 10500000, discount: "12%", rating: "4.5", reviews: "58", image: "https://images.pexels.com/photos/4846097/pexels-photo-4846097.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Sofa", room: "living", material: "Kain poliester tenun, rangka lipat logam, busa high density", dimensions: "Lebar 190 cm × Dalam 95 cm × Tinggi 78 cm", description: "Sofa dua dudukan yang bisa diubah menjadi kasur datar untuk tamu. Sandarannya bisa dilipat tanpa melepas bantal." },
  { id: "sofa-ranu-3s", name: "Ranu Sofa 3 Dudukan", price: 8150000, oldPrice: 9400000, discount: "13%", rating: "4.8", reviews: "112", image: "https://images.pexels.com/photos/4857775/pexels-photo-4857775.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Sofa", room: "living", material: "Kain velvet poliester, kaki beech solid, busa high density", dimensions: "Lebar 200 cm × Dalam 90 cm × Tinggi 84 cm", description: "Bentuk mid-century dengan kaki kayu meruncing dan satu bantal memanjang. Berlapis kain velvet lembut." },
  { id: "sofa-tala-compact", name: "Tala Sofa Kompak 2 Dudukan", price: 4750000, rating: "4.6", reviews: "39", image: "https://images.pexels.com/photos/39828916/pexels-photo-39828916.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Sofa", room: "living", material: "Campuran linen poliester, rangka pinus solid, busa high density", dimensions: "Lebar 145 cm × Dalam 82 cm × Tinggi 76 cm", description: "Sofa dua dudukan sempit yang dirancang untuk apartemen studio. Sandaran rendah menjaga pandangan tetap terbuka di ruangan kecil." },
  { id: "sofa-wijaya-4s", name: "Wijaya Sofa 4 Dudukan", price: 13800000, oldPrice: 15600000, discount: "12%", rating: "4.7", reviews: "83", image: "https://images.pexels.com/photos/4469171/pexels-photo-4469171.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Sofa", room: "living", material: "Kain tenun, rangka kayu mahoni solid, busa pocket spring", dimensions: "Lebar 245 cm × Dalam 95 cm × Tinggi 85 cm", description: "Sofa empat dudukan dengan dudukan lebar dan busa tebal. Sarungnya bisa dilepas dengan resleting tersembunyi di panel belakang." },
  { id: "armchair-kirana-wing", name: "Kursi Kirana Wingback", price: 3650000, oldPrice: 4200000, discount: "13%", rating: "4.7", reviews: "68", image: "https://images.pexels.com/photos/33646085/pexels-photo-33646085.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Santai", room: "living", material: "Campuran linen, rangka beech solid, busa high density", dimensions: "Lebar 78 cm × Dalam 82 cm × Tinggi 105 cm", description: "Kursi bersandar tinggi dengan dudukan padat dan lengan melengkung. Cocok untuk sudut baca atau sisi kamar tidur." },
  { id: "armchair-jalu-accent", name: "Kursi Aksen Jalu", price: 2450000, rating: "4.5", reviews: "54", image: "https://images.pexels.com/photos/7195580/pexels-photo-7195580.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Santai", room: "living", material: "Kain velvet poliester, cangkang plywood, kaki baja powder coating", dimensions: "Lebar 72 cm × Dalam 75 cm × Tinggi 80 cm", description: "Kursi aksen kecil dengan kaki logam hitam ramping. Cukup ringan untuk dipindah antar ruangan sendiri." },
  { id: "armchair-padi-rattan", name: "Kursi Rotan Padi", price: 2850000, oldPrice: 3300000, discount: "14%", rating: "4.6", reviews: "77", image: "https://images.pexels.com/photos/18258470/pexels-photo-18258470.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Santai", room: "living", material: "Rotan alami, kaki jati solid, bantal katun", dimensions: "Lebar 70 cm × Dalam 78 cm × Tinggi 86 cm", description: "Kursi rotan anyaman tangan dengan sandaran melengkung dan bantal dudukan yang bisa dilepas. Sebaiknya dijauhkan dari hujan langsung." },
  { id: "armchair-sena-lounge", name: "Kursi Santai Sena", price: 5200000, rating: "4.9", reviews: "88", image: "https://images.pexels.com/photos/13806257/pexels-photo-13806257.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Santai", room: "living", material: "Kain boucle, rangka kayu oak solid, dudukan pocket spring", dimensions: "Lebar 82 cm × Dalam 88 cm × Tinggi 92 cm", description: "Kursi santai lebar dengan dudukan rendah dan sandaran dalam. Pelapisnya boucle padat yang tahan berbulu." },
  { id: "armchair-embun-swivel", name: "Kursi Putar Embun", price: 3950000, oldPrice: 4600000, discount: "14%", rating: "4.7", reviews: "61", image: "https://images.pexels.com/photos/2079246/pexels-photo-2079246.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Santai", room: "living", material: "Kain microfiber, cangkang busa cetak, alas putar logam", dimensions: "Lebar 76 cm × Dalam 78 cm × Tinggi 74 cm", description: "Kursi ringkas yang bisa berputar penuh pada alas logam bulat. Dudukannya kembali ke tengah saat dilepas." },
  { id: "coffee-table-riko-round", name: "Meja Kopi Bundar Riko", price: 2650000, oldPrice: 3100000, discount: "15%", rating: "4.8", reviews: "134", image: "https://images.pexels.com/photos/7607461/pexels-photo-7607461.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Tamu", room: "living", material: "Permukaan marmer, alas baja powder coating", dimensions: "Diameter 80 cm × Tinggi 40 cm", description: "Meja kopi bundar dengan permukaan marmer dan alas baja hitam. Sisi bundarnya lebih aman di tata duduk yang sempit." },
  { id: "coffee-table-maru-nesting", name: "Set Meja Kopi Nesting Maru", price: 3450000, rating: "4.7", reviews: "52", image: "https://images.pexels.com/photos/15569230/pexels-photo-15569230.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Tamu", room: "living", material: "Permukaan veneer oak, kaki kayu solid", dimensions: "Lebar 70 cm × Dalam 70 cm × Tinggi 45 cm", description: "Set dua meja nesting yang bisa saling diselipkan. Berguna sebagai permukaan tambahan saat ada tamu." },
  { id: "coffee-table-bening-glass", name: "Meja Kopi Kaca Bening", price: 1950000, oldPrice: 2300000, discount: "15%", rating: "4.6", reviews: "73", image: "https://images.pexels.com/photos/14495885/pexels-photo-14495885.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Tamu", room: "living", material: "Kaca tempered, rangka kayu jati solid", dimensions: "Lebar 110 cm × Dalam 60 cm × Tinggi 42 cm", description: "Meja kopi persegi panjang dengan permukaan kaca tempered delapan milimeter. Permukaan bening membuat ruangan kecil terasa lebih lapang." },
  { id: "coffee-table-kala-lift", name: "Meja Kopi Lift-Top Kala", price: 2250000, rating: "4.5", reviews: "46", image: "https://images.pexels.com/photos/26546549/pexels-photo-26546549.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Tamu", room: "living", material: "Veneer kayu olahan, mekanisme lift baja", dimensions: "Lebar 100 cm × Dalam 55 cm × Tinggi 45 cm", description: "Meja lift-top dengan ruang penyimpanan di bawahnya. Permukaannya bisa naik ke ketinggian nyaman untuk bekerja." },
  { id: "coffee-table-laras-slim", name: "Meja Kopi Ramping Laras", price: 1550000, rating: "4.6", reviews: "41", image: "https://images.pexels.com/photos/5490904/pexels-photo-5490904.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Tamu", room: "living", material: "Papan kayu jati solid, finishing lacquer matte", dimensions: "Lebar 120 cm × Dalam 40 cm × Tinggi 38 cm", description: "Meja ramping berpapan yang pas di sepanjang sofa. Papan jati solid diletakkan di atas rangka terbuka sederhana." },
  { id: "tv-rack-vera-160", name: "Rak TV Vera 160 cm", price: 2750000, oldPrice: 3200000, discount: "14%", rating: "4.8", reviews: "148", image: "https://images.pexels.com/photos/14715846/pexels-photo-14715846.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja TV", room: "living", material: "Kayu olahan dengan veneer, kaki baja powder coating", dimensions: "Lebar 160 cm × Dalam 40 cm × Tinggi 45 cm", description: "Rak TV untuk televisi hingga 65 inci. Dua rak terbuka dan satu lemari tertutup menjaga remote dan kabel tetap rapi." },
  { id: "tv-rack-galuh-float", name: "Rak TV Gantung Galuh", price: 3150000, rating: "4.6", reviews: "57", image: "https://images.pexels.com/photos/6020432/pexels-photo-6020432.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja TV", room: "living", material: "Kayu olahan, finishing laminat matte", dimensions: "Lebar 180 cm × Dalam 35 cm × Tinggi 35 cm", description: "Rak TV gantung di dinding sehingga lantai tetap lega. Braket dan alat pasang disertakan untuk dinding bata dan rangka kayu." },
  { id: "tv-rack-surya-120", name: "Rak TV Surya 120 cm", price: 1850000, rating: "4.5", reviews: "44", image: "https://images.pexels.com/photos/35264779/pexels-photo-35264779.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja TV", room: "living", material: "Kayu olahan, kaki kayu solid", dimensions: "Lebar 120 cm × Dalam 38 cm × Tinggi 42 cm", description: "Rak TV rendah untuk televisi hingga 50 inci. Dua laci berjalan di rel logam dengan penahan tutup lembut." },
  { id: "tv-rack-nadi-corner", name: "Rak TV Sudut Nadi", price: 2350000, oldPrice: 2800000, discount: "16%", rating: "4.6", reviews: "49", image: "https://images.pexels.com/photos/36871613/pexels-photo-36871613.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja TV", room: "living", material: "Veneer kayu olahan, rangka baja", dimensions: "Lebar 140 cm × Dalam 45 cm × Tinggi 50 cm", description: "Rak TV bersudut yang dirancang untuk sudut ruangan. Bentuk segitiganya memanfaatkan ruang yang biasanya terbuang." },
  { id: "tv-rack-purnama-200", name: "Rak TV Purnama 200 cm", price: 4600000, rating: "4.7", reviews: "66", image: "https://images.pexels.com/photos/7214734/pexels-photo-7214734.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja TV", room: "living", material: "Kayu olahan veneer walnut, kaki kayu solid", dimensions: "Lebar 200 cm × Dalam 42 cm × Tinggi 48 cm", description: "Rak TV lebar untuk televisi besar dan perangkat audio. Empat pintu soft-close menyembunyikan semua barang di baliknya." },
  { id: "side-table-nila-round", name: "Meja Samping Bundar Nila", price: 950000, oldPrice: 1150000, discount: "17%", rating: "4.7", reviews: "119", image: "https://images.pexels.com/photos/14063637/pexels-photo-14063637.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "living", material: "Baja powder coating, permukaan kayu olahan", dimensions: "Diameter 45 cm × Tinggi 55 cm", description: "Meja bundar kecil yang diletakkan di samping sofa atau tempat tidur. Tepinya berbingkai agar gelas tidak mudah jatuh." },
  { id: "side-table-mutiara-nesting", name: "Set Meja Samping Nesting Mutiara", price: 1650000, rating: "4.6", reviews: "58", image: "https://images.pexels.com/photos/6078539/pexels-photo-6078539.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "living", material: "MDF dengan veneer, kaki kayu solid", dimensions: "Lebar 50 cm × Dalam 50 cm × Tinggi 52 cm", description: "Sepasang meja samping nesting dengan dua ketinggian. Yang kecil bisa masuk sepenuhnya di bawah yang tinggi." },
  { id: "side-table-angsa-cement", name: "Meja Samping Semen Angsa", price: 780000, rating: "4.5", reviews: "36", image: "https://images.pexels.com/photos/545048/pexels-photo-545048.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "living", material: "Permukaan fibre cement, kaki baja powder coating", dimensions: "Diameter 38 cm × Tinggi 48 cm", description: "Meja kecil bergaya semen dengan permukaan bertekstur matte. Finishing betonnya dilapisi pelindung anti tumpahan." },
  { id: "side-table-kembang-drawer", name: "Meja Samping Berlaci Kembang", price: 1250000, oldPrice: 1450000, discount: "14%", rating: "4.6", reviews: "63", image: "https://images.pexels.com/photos/12277215/pexels-photo-12277215.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "living", material: "Kayu olahan, kaki kayu solid, rel laci logam", dimensions: "Lebar 42 cm × Dalam 40 cm × Tinggi 58 cm", description: "Meja samping tinggi dengan satu laci untuk barang kecil. Bisa dipakai sebagai meja samping tempat tidur di ruangan sempit." },
  { id: "side-table-sisi-cshape", name: "Meja Samping Bentuk C Sisi", price: 1450000, rating: "4.5", reviews: "47", image: "https://images.pexels.com/photos/5570227/pexels-photo-5570227.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "living", material: "Permukaan marmer, rangka baja powder coating", dimensions: "Lebar 45 cm × Dalam 35 cm × Tinggi 60 cm", description: "Meja bentuk C yang bisa diselipkan di atas lengan sofa. Permukaan marmernya bertumpu pada rangka baja gold ramping." },
  { id: "bed-frame-evora-queen", name: "Evora Rangka Tempat Tidur Queen", price: 6999000, oldPrice: 7799000, discount: "10%", rating: "4.8", reviews: "126", image: "https://images.pexels.com/photos/30287057/pexels-photo-30287057.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rangka Tempat Tidur", room: "bedroom", material: "Veneer oak, slat kayu solid", dimensions: "Lebar 172 cm × Dalam 212 cm × Tinggi 110 cm", description: "Rangka tempat tidur queen dengan sandaran oak rendah dan slat kayu solid. Dikirim bongkar dan butuh sekitar empat puluh menit untuk dirakit." },
  { id: "bed-frame-nadi-king", name: "Nadi Rangka Tempat Tidur King", price: 9300000, oldPrice: 10400000, discount: "11%", rating: "4.7", reviews: "88", image: "https://images.pexels.com/photos/35505496/pexels-photo-35505496.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rangka Tempat Tidur", room: "bedroom", material: "Veneer walnut, slat plywood", dimensions: "Lebar 192 cm × Dalam 212 cm × Tinggi 120 cm", description: "Rangka king berbahan veneer walnut gelap dengan sandaran tinggi berslat. Rel penopang tengah menjaga kasur lebar tetap rata." },
  { id: "bed-frame-rimbun-double", name: "Rimbun Rangka Tempat Tidur Double", price: 5400000, rating: "4.6", reviews: "54", image: "https://images.pexels.com/photos/36657301/pexels-photo-36657301.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rangka Tempat Tidur", room: "bedroom", material: "Kayu jati solid", dimensions: "Lebar 132 cm × Dalam 202 cm × Tinggi 90 cm", description: "Rangka tempat tidur double dari kayu jati solid dengan sandaran kotak polos. Serat jati tiap unit bisa berbeda." },
  { id: "bed-frame-kalista-single", name: "Kalista Rangka Tempat Tidur Single", price: 3450000, oldPrice: 3900000, discount: "12%", rating: "4.5", reviews: "37", image: "https://images.pexels.com/photos/7214474/pexels-photo-7214474.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rangka Tempat Tidur", room: "bedroom", material: "Veneer birch, baja lapis powder", dimensions: "Lebar 112 cm × Dalam 202 cm × Tinggi 85 cm", description: "Rangka single dengan kaki baja lapis powder dan sandaran birch pucat. Cocok untuk kamar mungil dan sudut tamu." },
  { id: "bed-frame-selatan-queen-storage", name: "Selatan Rangka Tempat Tidur Queen dengan Penyimpanan", price: 9750000, rating: "4.8", reviews: "112", image: "https://images.pexels.com/photos/12904231/pexels-photo-12904231.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rangka Tempat Tidur", room: "bedroom", material: "Kain pelapis, papan partikel", dimensions: "Lebar 172 cm × Dalam 216 cm × Tinggi 115 cm", description: "Rangka queen dengan dua laci di bagian dasar dan sandaran berlapis kain penuh. Laci berjalan di rel logam." },
  { id: "bed-frame-laras-king-upholstered", name: "Laras Rangka Tempat Tidur King Berlapis Kain", price: 11400000, oldPrice: 12600000, discount: "10%", rating: "4.9", reviews: "64", image: "https://images.pexels.com/photos/29640156/pexels-photo-29640156.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rangka Tempat Tidur", room: "bedroom", material: "Linen tenun, rangka kayu solid", dimensions: "Lebar 196 cm × Dalam 216 cm × Tinggi 125 cm", description: "Rangka king berlapis linen tenun dengan sandaran bertufting berkanal dalam. Slat menempel tetap di rel samping." },
  { id: "bed-frame-bumi-queen-platform", name: "Bumi Rangka Tempat Tidur Queen Platform", price: 4200000, rating: "4.6", reviews: "29", image: "https://images.pexels.com/photos/4300056/pexels-photo-4300056.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rangka Tempat Tidur", room: "bedroom", material: "Kayu karet, slat tali anyam", dimensions: "Lebar 168 cm × Dalam 208 cm × Tinggi 35 cm", description: "Rangka platform rendah dari kayu karet tanpa sandaran, sehingga kasur duduk dekat lantai. Slat disatukan tali anyam." },
  { id: "mattress-cendana-160-foam", name: "Kasur Busa Cendana 160 x 200", price: 3450000, oldPrice: 3990000, discount: "14%", rating: "4.7", reviews: "158", image: "https://images.pexels.com/photos/8089076/pexels-photo-8089076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kasur", room: "bedroom", material: "Busa densitas tinggi, sarung rajutan", dimensions: "Lebar 160 cm × Dalam 200 cm × Tinggi 20 cm", description: "Kasur busa medium-firm ukuran 160 x 200 cm dengan sarung rajutan yang bisa dilepas. Cocok untuk rangka queen berslat standar." },
  { id: "mattress-arunika-180-pocket-spring", name: "Kasur Pocket Spring Arunika 180 x 200", price: 12800000, oldPrice: 14500000, discount: "12%", rating: "4.8", reviews: "96", image: "https://images.pexels.com/photos/26840829/pexels-photo-26840829.png?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kasur", room: "bedroom", material: "Per pocket spring, kain quilted", dimensions: "Lebar 180 cm × Dalam 200 cm × Tinggi 26 cm", description: "Kasur pocket spring ukuran king dengan permukaan quilted dan penopang tepi. Tiap per bergerak sendiri untuk menekan getaran." },
  { id: "mattress-melati-120-spring", name: "Kasur Spring Melati 120 x 200", price: 2950000, rating: "4.5", reviews: "71", image: "https://images.pexels.com/photos/6920442/pexels-photo-6920442.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kasur", room: "bedroom", material: "Per bonnell, sarung katun", dimensions: "Lebar 120 cm × Dalam 200 cm × Tinggi 18 cm", description: "Kasur spring bonnell ukuran double dengan rasa keras dan sarung katun polos. Pas untuk rangka tempat tidur double." },
  { id: "mattress-tirta-100-foam", name: "Kasur Busa Tirta 100 x 200", price: 2150000, oldPrice: 2490000, discount: "14%", rating: "4.6", reviews: "83", image: "https://images.pexels.com/photos/7614416/pexels-photo-7614416.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kasur", room: "bedroom", material: "Busa rebonded, sarung poliester", dimensions: "Lebar 100 cm × Dalam 200 cm × Tinggi 15 cm", description: "Kasur busa single untuk kamar anak dan tempat tidur tamu. Sarungnya bisa dibuka resleting dan dicuci air dingin." },
  { id: "mattress-sagara-160-latex", name: "Kasur Latex Sagara 160 x 200", price: 8900000, oldPrice: 9600000, discount: "7%", rating: "4.9", reviews: "47", image: "https://images.pexels.com/photos/8089071/pexels-photo-8089071.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kasur", room: "bedroom", material: "Latex alami, sarung quilted", dimensions: "Lebar 160 cm × Dalam 200 cm × Tinggi 22 cm", description: "Kasur latex queen dengan inti berlubang yang bernapas dan permukaan quilted lembut. Latex terasa lebih sejuk dari busa padat." },
  { id: "wardrobe-ambar-3-door", name: "Lemari Pakaian Ambar 3 Pintu", price: 4850000, oldPrice: 5450000, discount: "11%", rating: "4.7", reviews: "134", image: "https://images.pexels.com/photos/39733041/pexels-photo-39733041.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Pakaian", room: "bedroom", material: "Papan partikel, finishing melamin", dimensions: "Lebar 150 cm × Dalam 55 cm × Tinggi 200 cm", description: "Lemari tiga pintu dengan dua rel gantung dan empat rak. Pintunya model engsel dan terbuka sekitar 100 derajat." },
  { id: "wardrobe-nusa-2-door-mirror", name: "Lemari Pakaian Nusa 2 Pintu dengan Cermin", price: 3950000, rating: "4.6", reviews: "78", image: "https://images.pexels.com/photos/7061419/pexels-photo-7061419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Pakaian", room: "bedroom", material: "Kayu olahan, cermin kaca", dimensions: "Lebar 100 cm × Dalam 52 cm × Tinggi 195 cm", description: "Lemari dua pintu dengan cermin setinggi pintu kanan dan satu laci di dalam. Rel gantung ada di dua ketinggian." },
  { id: "wardrobe-kinari-4-door-sliding", name: "Lemari Pakaian Geser Kinari 4 Pintu", price: 8950000, oldPrice: 9900000, discount: "10%", rating: "4.8", reviews: "59", image: "https://images.pexels.com/photos/6580395/pexels-photo-6580395.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Pakaian", room: "bedroom", material: "Papan partikel, rel aluminium", dimensions: "Lebar 200 cm × Dalam 60 cm × Tinggi 210 cm", description: "Lemari geser empat panel yang tidak butuh ruang bukaan pintu. Di dalamnya ada dua rel dan lima rak." },
  { id: "wardrobe-jati-lestari-2-door", name: "Lemari Pakaian Jati Lestari 2 Pintu", price: 11200000, rating: "4.9", reviews: "33", image: "https://images.pexels.com/photos/5705496/pexels-photo-5705496.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Pakaian", room: "bedroom", material: "Kayu jati solid", dimensions: "Lebar 110 cm × Dalam 58 cm × Tinggi 190 cm", description: "Lemari kayu jati solid dengan pintu panel timbul dan rak berslat untuk sepatu di bagian bawah." },
  { id: "wardrobe-pinus-2-door-kids", name: "Lemari Pakaian Anak Pinus 2 Pintu", price: 3150000, oldPrice: 3550000, discount: "11%", rating: "4.6", reviews: "41", image: "https://images.pexels.com/photos/18725622/pexels-photo-18725622.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Pakaian", room: "bedroom", material: "Kayu pinus, cat berbasis air", dimensions: "Lebar 90 cm × Dalam 48 cm × Tinggi 150 cm", description: "Lemari dua pintu pendek berukuran untuk anak, sudutnya tumpul dan rel gantung rendah yang mudah dijangkau." },
  { id: "wardrobe-ashari-3-door-open-shelf", name: "Lemari Pakaian Ashari 3 Pintu dengan Rak Terbuka", price: 6350000, rating: "4.7", reviews: "67", image: "https://images.pexels.com/photos/6508349/pexels-photo-6508349.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Pakaian", room: "bedroom", material: "Papan partikel, rel laci baja", dimensions: "Lebar 140 cm × Dalam 55 cm × Tinggi 205 cm", description: "Lemari tiga pintu dengan rak terbuka di atas untuk tas dan lipatan kain. Dua laci bawah berjalan di rel baja." },
  { id: "nightstand-nadi-oak", name: "Nadi Meja Samping Oak", price: 1450000, oldPrice: 1690000, discount: "14%", rating: "4.8", reviews: "142", image: "https://images.pexels.com/photos/26840825/pexels-photo-26840825.png?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "bedroom", material: "Veneer oak, kaki kayu solid", dimensions: "Lebar 45 cm × Dalam 40 cm × Tinggi 55 cm", description: "Meja samping oak dengan dua laci di rel kayu dan kolong terbuka di bawah. Sejajar dengan rangka tempat tidur rendah." },
  { id: "nightstand-kinari-softclose-grey", name: "Kinari Meja Samping Soft-Close", price: 1690000, rating: "4.7", reviews: "88", image: "https://images.pexels.com/photos/7166560/pexels-photo-7166560.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "bedroom", material: "Kayu olahan, laker", dimensions: "Lebar 48 cm × Dalam 42 cm × Tinggi 58 cm", description: "Meja samping abu-abu dengan dua laci soft-close dan permukaan atas berlaker. Laci terbuka penuh di rel baja." },
  { id: "nightstand-rimbun-teak-stool", name: "Rimbun Bangku Samping Jati", price: 780000, oldPrice: 890000, discount: "12%", rating: "4.6", reviews: "53", image: "https://images.pexels.com/photos/9819651/pexels-photo-9819651.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "bedroom", material: "Kayu jati solid", dimensions: "Lebar 38 cm × Dalam 38 cm × Tinggi 50 cm", description: "Bangku jati mungil untuk meja samping, dengan satu rak terselip di bawah dudukan. Tanpa laci atau besi." },
  { id: "nightstand-laras-upholstered-drawer", name: "Laras Meja Samping Berlapis Kain", price: 2350000, oldPrice: 2650000, discount: "11%", rating: "4.9", reviews: "36", image: "https://images.pexels.com/photos/6947279/pexels-photo-6947279.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "bedroom", material: "Kain linen, badan kayu", dimensions: "Lebar 52 cm × Dalam 44 cm × Tinggi 56 cm", description: "Meja samping berlapis linen di atas badan kayu solid, dengan satu laci dalam dan sisipan batu di atasnya." },
  { id: "nightstand-tirta-kids-round", name: "Tirta Meja Samping Anak Bulat", price: 875000, rating: "4.5", reviews: "24", image: "https://images.pexels.com/photos/545046/pexels-photo-545046.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Samping", room: "bedroom", material: "Kayu pinus, cat berbasis air", dimensions: "Lebar 40 cm × Dalam 40 cm × Tinggi 48 cm", description: "Meja samping pinus bulat untuk kamar anak dengan satu rak terbuka dan permukaan bercat. Tepinya disanding bulat." },
  { id: "dining-table-arka-4seat", name: "Arka Meja Makan Set 4 Kursi", price: 5999000, oldPrice: 6499000, discount: "8%", rating: "4.8", reviews: "126", image: "https://images.pexels.com/photos/35833817/pexels-photo-35833817.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Makan", room: "dining", material: "Kayu rubberwood solid, inti kayu olahan", dimensions: "Panjang 140 cm × Lebar 80 cm × Tinggi 75 cm", description: "Meja empat kursi dengan permukaan kayu rubberwood solid dan kaki meruncing. Dikirim bongkar dan butuh sekitar dua puluh menit untuk dirakit." },
  { id: "dining-table-gading-round-120", name: "Gading Meja Makan Bundar 120", price: 8999000, oldPrice: 9799000, discount: "8%", rating: "4.7", reviews: "74", image: "https://images.pexels.com/photos/7180275/pexels-photo-7180275.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Makan", room: "dining", material: "Permukaan batu olahan, kaki kayu rubberwood solid", dimensions: "Diameter 120 cm × Tinggi 75 cm", description: "Meja bundar dengan permukaan bercorak terrazzo di atas empat kaki kayu solid. Nyaman untuk empat orang dan mudah dilap setelah makan." },
  { id: "dining-table-lento-extendable-160", name: "Lento Meja Makan Extendable 160", price: 11990000, oldPrice: 12990000, discount: "8%", rating: "4.9", reviews: "41", image: "https://images.pexels.com/photos/27897030/pexels-photo-27897030.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Makan", room: "dining", material: "Veneer walnut, inti kayu olahan, mekanisme daun baja", dimensions: "Panjang 160–200 cm × Lebar 90 cm × Tinggi 75 cm", description: "Meja veneer walnut yang memanjang dari 160 ke 200 cm dengan mengangkat daun tengahnya. Muat enam orang, delapan saat dipanjangkan." },
  { id: "dining-table-bayu-compact-80", name: "Bayu Meja Makan Ringkas Dua Orang", price: 3299000, rating: "4.6", reviews: "92", image: "https://images.pexels.com/photos/31138742/pexels-photo-31138742.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Makan", room: "dining", material: "Kayu jati solid", dimensions: "Panjang 80 cm × Lebar 80 cm × Tinggi 75 cm", description: "Meja persegi untuk dua orang, dibuat dari kayu jati solid dengan finishing matte. Pas untuk balkon kecil dan sudut dapur." },
  { id: "dining-table-cakra-6seat", name: "Cakra Meja Makan 6 Kursi", price: 9499000, oldPrice: 10499000, discount: "10%", rating: "4.7", reviews: "58", image: "https://images.pexels.com/photos/5676261/pexels-photo-5676261.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Makan", room: "dining", material: "Kayu akasia solid, baja lapis powder coating", dimensions: "Panjang 180 cm × Lebar 90 cm × Tinggi 76 cm", description: "Meja enam kursi dengan permukaan akasia di atas rangka baja hitam lapis powder coating. Permukaannya sudah dilubangi untuk pemasangan kaki." },
  { id: "dining-table-damai-pedestal-100", name: "Damai Meja Makan Bundar Tiang Tengah", price: 4999000, oldPrice: 5499000, discount: "9%", rating: "4.6", reviews: "113", image: "https://images.pexels.com/photos/4946676/pexels-photo-4946676.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Makan", room: "dining", material: "Kayu olahan berlapis laminat tersegel, tiang dan alas baja", dimensions: "Diameter 100 cm × Tinggi 74 cm", description: "Meja bundar dengan satu tiang tengah, jadi tidak ada yang duduk tepat di atas kaki meja. Permukaan tersegelnya tahan tumpahan sehari-hari." },
  { id: "dining-chair-elok-upholstered", name: "Elok Kursi Makan Berlapis Kain", price: 1299000, oldPrice: 1499000, discount: "13%", rating: "4.8", reviews: "147", image: "https://images.pexels.com/photos/29917912/pexels-photo-29917912.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Makan", room: "dining", material: "Campuran linen poliester, rangka kayu rubberwood solid, busa", dimensions: "Lebar 46 cm × Dalam 54 cm × Tinggi 82 cm", description: "Kursi makan dengan dudukan dan sandaran berbusa di atas rangka kayu solid. Tinggi duduk 47 cm, pas untuk meja standar." },
  { id: "dining-chair-riang-rattan", name: "Riang Kursi Makan Rotan", price: 899000, oldPrice: 999000, discount: "10%", rating: "4.6", reviews: "61", image: "https://images.pexels.com/photos/6969827/pexels-photo-6969827.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Makan", room: "dining", material: "Rotan natural, rangka dudukan kayu solid", dimensions: "Lebar 50 cm × Dalam 55 cm × Tinggi 80 cm", description: "Kursi rotan anyaman tangan dengan sandaran melengkung dan dudukan anyam. Cukup ringan untuk diangkat dan ditumpuk dengan satu tangan." },
  { id: "dining-chair-puja-stackable", name: "Puja Kursi Makan Bisa Ditumpuk", price: 649000, rating: "4.5", reviews: "120", image: "https://images.pexels.com/photos/3935326/pexels-photo-3935326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Makan", room: "dining", material: "Polipropilena daur ulang, kaki baja", dimensions: "Lebar 45 cm × Dalam 50 cm × Tinggi 79 cm", description: "Dicetak satu bagian dari polipropilena daur ulang dengan sandaran sedikit lentur. Bisa ditumpuk sampai enam dan mudah dibilas di luar." },
  { id: "dining-chair-kemuning-bench", name: "Kemuning Bangku Makan", price: 1699000, oldPrice: 1899000, discount: "11%", rating: "4.7", reviews: "39", image: "https://images.pexels.com/photos/6920630/pexels-photo-6920630.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Makan", room: "dining", material: "Oak solid, permukaan veneer oak", dimensions: "Panjang 120 cm × Dalam 38 cm × Tinggi 45 cm", description: "Bangku tanpa sandaran dari oak solid yang bisa diselipkan ke bawah meja. Muat dua orang dewasa atau tiga anak." },
  { id: "dining-chair-kencana-velvet", name: "Kencana Kursi Makan Beludru", price: 1899000, oldPrice: 2199000, discount: "14%", rating: "4.8", reviews: "88", image: "https://images.pexels.com/photos/7061405/pexels-photo-7061405.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Makan", room: "dining", material: "Beludru poliester, rangka baja finishing kuningan", dimensions: "Lebar 48 cm × Dalam 56 cm × Tinggi 84 cm", description: "Kursi beludru dengan rangka baja finishing kuningan dan sandaran melengkung tipis. Bantalan duduknya bisa dilepas untuk dibersihkan setempat." },
  { id: "desk-aksara-120", name: "Aksara Meja Tulis 120", price: 2799000, oldPrice: 3199000, discount: "13%", rating: "4.7", reviews: "104", image: "https://images.pexels.com/photos/36123565/pexels-photo-36123565.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Kerja", room: "workspace", material: "Permukaan kayu rubberwood solid, laci kayu olahan, kaki baja", dimensions: "Panjang 120 cm × Lebar 55 cm × Tinggi 75 cm", description: "Meja tulis dengan satu laci soft-close, lubang kabel di bagian belakang, dan permukaan kayu rubberwood solid." },
  { id: "desk-palapa-standing-140", name: "Palapa Meja Berdiri 140", price: 5799000, oldPrice: 6499000, discount: "11%", rating: "4.9", reviews: "52", image: "https://images.pexels.com/photos/19055620/pexels-photo-19055620.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Kerja", room: "workspace", material: "Permukaan kayu olahan, rangka baja lapis powder coating", dimensions: "Panjang 140 cm × Lebar 70 cm × Tinggi 71–120 cm", description: "Meja berdiri elektrik dengan dua motor yang mengangkat permukaan antara 71 dan 120 cm. Empat preset memori dan penghenti anti-benturan." },
  { id: "desk-kemang-140-hutch", name: "Kemang Meja Kerja dengan Rak 140", price: 4299000, rating: "4.6", reviews: "67", image: "https://images.pexels.com/photos/13075330/pexels-photo-13075330.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Kerja", room: "workspace", material: "Veneer oak, badan kayu olahan", dimensions: "Panjang 140 cm × Lebar 60 cm × Tinggi 75 cm", description: "Meja kerja dengan rak hutch di atas dan dua laci bawah. Binder disimpan di rak atas supaya permukaan meja tetap lega." },
  { id: "desk-sinar-compact-90", name: "Sinar Meja Ringkas 90", price: 1599000, oldPrice: 1799000, discount: "11%", rating: "4.5", reviews: "131", image: "https://images.pexels.com/photos/1128207/pexels-photo-1128207.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Kerja", room: "workspace", material: "Kayu olahan, kaki pinus", dimensions: "Panjang 90 cm × Lebar 45 cm × Tinggi 75 cm", description: "Meja kecil untuk ruangan sempit, dengan satu laci dan rak yang muat laptop di bawahnya. Dirakit dengan kunci L bawaan." },
  { id: "desk-waluya-corner-l", name: "Waluya Meja Sudut Bentuk L", price: 3499000, oldPrice: 3999000, discount: "13%", rating: "4.7", reviews: "45", image: "https://images.pexels.com/photos/15062127/pexels-photo-15062127.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Kerja", room: "workspace", material: "Kayu olahan, kaki baja lapis powder coating", dimensions: "Panjang 150 cm × Lebar 120 cm × Tinggi 75 cm", description: "Meja sudut yang pas di pertemuan dinding sembilan puluh derajat dan menyisakan ruang untuk monitor serta printer." },
  { id: "desk-rakha-teak-130", name: "Rakha Meja Jati Solid 130", price: 5199000, oldPrice: 5599000, discount: "7%", rating: "4.8", reviews: "29", image: "https://images.pexels.com/photos/6265942/pexels-photo-6265942.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Meja Kerja", room: "workspace", material: "Kayu jati solid", dimensions: "Panjang 130 cm × Lebar 60 cm × Tinggi 76 cm", description: "Meja jati solid dengan serat kayu terlihat, laci tengah dangkal, dan saluran kabel terbuka di rel belakang." },
  { id: "office-chair-giri-mesh-midback", name: "Giri Kursi Kantor Mesh Punggung Sedang", price: 1899000, oldPrice: 2199000, discount: "14%", rating: "4.7", reviews: "158", image: "https://images.pexels.com/photos/295480/pexels-photo-295480.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Kerja", room: "workspace", material: "Mesh nilon, dudukan busa cetak, alas nilon", dimensions: "Lebar 64 cm × Dalam 62 cm × Tinggi duduk 44–54 cm", description: "Kursi mesh punggung sedang dengan bantalan lumbar, tinggi duduk yang bisa diatur, dan pengunci rebahan. Dudukan bergerak antara 44 dan 54 cm." },
  { id: "office-chair-swara-ergo-highback", name: "Swara Kursi Ergonomis Punggung Tinggi", price: 4299000, oldPrice: 4799000, discount: "10%", rating: "4.8", reviews: "76", image: "https://images.pexels.com/photos/36149083/pexels-photo-36149083.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Kerja", room: "workspace", material: "Mesh elastomer, alas aluminium, busa cetak", dimensions: "Lebar 68 cm × Dalam 68 cm × Tinggi duduk 46–56 cm", description: "Kursi punggung tinggi dengan lumbar yang bisa diatur, synchro-tilt, dan panel mesh berangin. Tinggi duduk 46 sampai 56 cm." },
  { id: "office-chair-aksa-executive-leather", name: "Aksa Kursi Eksekutif Kulit", price: 6499000, oldPrice: 6999000, discount: "7%", rating: "4.9", reviews: "34", image: "https://images.pexels.com/photos/7071/space-desk-office-workspace.jpg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Kerja", room: "workspace", material: "Kulit bonded, rangka baja, alas aluminium", dimensions: "Lebar 70 cm × Dalam 72 cm × Tinggi duduk 45–55 cm", description: "Kursi eksekutif berbahan kulit bonded dengan sandaran kepala berbusa, kaki bintang lima, dan roda senyap untuk lantai keras." },
  { id: "office-chair-bentala-drafting-stool", name: "Bentala Kursi Drafting", price: 2299000, rating: "4.6", reviews: "48", image: "https://images.pexels.com/photos/5483245/pexels-photo-5483245.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Kerja", room: "workspace", material: "Busa cetak, alas nilon, foot ring krom", dimensions: "Lebar 58 cm × Dalam 58 cm × Tinggi duduk 55–75 cm", description: "Kursi drafting dengan foot ring krom dan dudukan yang bisa naik sampai 75 cm untuk meja setinggi berdiri." },
  { id: "office-chair-nahara-mesh-task", name: "Nahara Kursi Kerja Mesh", price: 1299000, oldPrice: 1499000, discount: "13%", rating: "4.5", reviews: "167", image: "https://images.pexels.com/photos/7534224/pexels-photo-7534224.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Kursi Kerja", room: "workspace", material: "Mesh nilon, dudukan busa, alas nilon", dimensions: "Lebar 60 cm × Dalam 58 cm × Tinggi duduk 43–53 cm", description: "Kursi kerja harian dengan sandaran mesh berangin, sandaran tangan tetap, dan dudukan berbusa untuk kerja lama di meja." },
  { id: "table-lamp-arli-ceramic", name: "Arli Lampu Meja Keramik", price: 549000, oldPrice: 649000, discount: "15%", rating: "4.7", reviews: "89", image: "https://images.pexels.com/photos/21612521/pexels-photo-21612521.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lampu Meja", room: "lighting", material: "Badan keramik berglasir, kap kain tenun", dimensions: "Diameter 28 cm × Tinggi 45 cm", description: "Lampu meja keramik dengan kap kain tenun dan saklar di kabel. Menggunakan bohlam E27 standar." },
  { id: "table-lamp-nirmala-wood", name: "Nirmala Lampu Meja Kayu", price: 729000, oldPrice: 799000, discount: "9%", rating: "4.6", reviews: "65", image: "https://images.pexels.com/photos/37252658/pexels-photo-37252658.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lampu Meja", room: "lighting", material: "Alas kayu rubberwood bubut, kap linen", dimensions: "Diameter 30 cm × Tinggi 50 cm", description: "Lampu meja dengan alas kayu bubut dan kap linen berbentuk drum yang menyebar cahaya rata di atas meja." },
  { id: "table-lamp-sore-dimmable-touch", name: "Sore Lampu Meja Peredup Sentuh", price: 899000, oldPrice: 999000, discount: "10%", rating: "4.8", reviews: "112", image: "https://images.pexels.com/photos/3852632/pexels-photo-3852632.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lampu Meja", room: "lighting", material: "Badan metal lapis powder coating, difuser akrilik", dimensions: "Diameter 22 cm × Tinggi 42 cm", description: "Lampu dengan peredup sentuh tiga tingkat kecerahan dan bohlam LED hangat yang sudah termasuk dalam kemasan." },
  { id: "table-lamp-bulan-glass-globe", name: "Bulan Lampu Meja Bola Kaca", price: 1299000, rating: "4.7", reviews: "43", image: "https://images.pexels.com/photos/19206473/pexels-photo-19206473.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lampu Meja", room: "lighting", material: "Bola kaca asap, batang baja finishing kuningan", dimensions: "Diameter 20 cm × Tinggi 34 cm", description: "Lampu berbentuk bola dari kaca asap dengan batang kuningan, memancarkan cahaya lembut di meja samping." },
  { id: "table-lamp-titian-clamp", name: "Titian Lampu Jepit Meja", price: 379000, oldPrice: 429000, discount: "12%", rating: "4.5", reviews: "138", image: "https://images.pexels.com/photos/5998056/pexels-photo-5998056.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lampu Meja", room: "lighting", material: "Baja lapis powder coating, bantalan jepit silikon", dimensions: "Lebar 12 cm × Dalam 40 cm × Tinggi 45 cm", description: "Lampu jepit dengan leher lentur yang bisa dipasang di rak setebal empat sentimeter." },
  { id: "cabinet-kana-low", name: "Kana Lemari Sideboard Pendek", price: 3999000, rating: "4.7", reviews: "59", image: "https://images.pexels.com/photos/9899846/pexels-photo-9899846.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Penyimpanan", room: "storage", material: "Veneer oak, badan kayu olahan, kaki metal", dimensions: "Lebar 150 cm × Dalam 42 cm × Tinggi 78 cm", description: "Sideboard pendek dengan dua pintu soft-close dan rak terbuka di bawah untuk perangkat media atau keranjang anyaman." },
  { id: "cabinet-biru-tall", name: "Biru Lemari Penyimpanan Tinggi", price: 5490000, rating: "4.8", reviews: "124", image: "https://images.pexels.com/photos/11643074/pexels-photo-11643074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Penyimpanan", room: "storage", material: "Veneer walnut, badan kayu olahan, kaki kayu solid", dimensions: "Lebar 90 cm × Dalam 40 cm × Tinggi 180 cm", description: "Lemari penyimpanan tinggi dengan empat rak yang bisa disetel di balik dua pintu, muat linen, perkakas, dan perlengkapan rumah." },
  { id: "cabinet-telu-2door", name: "Telu Sideboard Dua Pintu", price: 3299000, oldPrice: 3799000, discount: "13%", rating: "4.6", reviews: "47", image: "https://images.pexels.com/photos/7195582/pexels-photo-7195582.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Penyimpanan", room: "storage", material: "Kayu olahan, finishing lakuer matte, handle metal", dimensions: "Lebar 120 cm × Dalam 40 cm × Tinggi 75 cm", description: "Sideboard dua pintu yang ringkas untuk lorong sempit, dengan satu rak dalam yang membagi ruang jadi dua bagian." },
  { id: "cabinet-sekar-glass", name: "Sekar Lemari Display Pintu Kaca", price: 4750000, rating: "4.7", reviews: "88", image: "https://images.pexels.com/photos/7195588/pexels-photo-7195588.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Penyimpanan", room: "storage", material: "Kayu olahan, pintu kaca tempered, engsel baja", dimensions: "Lebar 100 cm × Dalam 42 cm × Tinggi 160 cm", description: "Lemari display dengan pintu kaca tempered dan tiga rak dalam untuk gelas, keramik, dan barang koleksi." },
  { id: "cabinet-lara-wide", name: "Lara Kabinet Media Lebar", price: 6290000, rating: "4.8", reviews: "142", image: "https://images.pexels.com/photos/10308499/pexels-photo-10308499.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Penyimpanan", room: "storage", material: "Veneer oak, badan kayu olahan, kaki baja powder coating", dimensions: "Lebar 180 cm × Dalam 45 cm × Tinggi 60 cm", description: "Kabinet media lebar dengan dua laci dan lubang kabel di belakang, pas diletakkan di bawah televisi berukuran besar." },
  { id: "cabinet-nusa-slim", name: "Nusa Lemari Lorong Ramping", price: 2190000, rating: "4.5", reviews: "33", image: "https://images.pexels.com/photos/8171932/pexels-photo-8171932.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Lemari Penyimpanan", room: "storage", material: "Kayu olahan, laminasi motif kayu, kaki metal", dimensions: "Lebar 60 cm × Dalam 35 cm × Tinggi 120 cm", description: "Lemari lorong ramping dengan satu laci dan satu pintu, cukup sempit untuk area masuk yang terbatas." },
  { id: "bookshelf-hana-4tier", name: "Hana Rak Buku 4 Tingkat", price: 1490000, rating: "4.7", reviews: "96", image: "https://images.pexels.com/photos/8045884/pexels-photo-8045884.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rak Buku", room: "storage", material: "Kayu olahan, rangka baja powder coating", dimensions: "Lebar 80 cm × Dalam 30 cm × Tinggi 160 cm", description: "Rak buku terbuka empat tingkat dengan rak atas tetap dan tiga rak yang bisa disetel, muat buku tipis dan tanaman kecil." },
  { id: "bookshelf-ria-5tier", name: "Ria Rak Buku Terbuka 5 Tingkat", price: 1890000, rating: "4.6", reviews: "71", image: "https://images.pexels.com/photos/38094564/pexels-photo-38094564.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rak Buku", room: "storage", material: "Rak kayu olahan, rangka baja", dimensions: "Lebar 70 cm × Dalam 28 cm × Tinggi 180 cm", description: "Rak terbuka lima tingkat dengan rangka baja ramping, cukup tinggi untuk menampung deretan novel di dinding." },
  { id: "bookshelf-maya-low", name: "Maya Rak Buku Pendek", price: 1250000, rating: "4.5", reviews: "38", image: "https://images.pexels.com/photos/18322095/pexels-photo-18322095.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rak Buku", room: "storage", material: "Kayu karet solid, panel belakang kayu olahan", dimensions: "Lebar 120 cm × Dalam 30 cm × Tinggi 80 cm", description: "Rak rendah dua tingkat setinggi bangku, dirancang untuk diletakkan di bawah jendela atau di samping sofa." },
  { id: "bookshelf-putra-ladder", name: "Putra Rak Buku Tangga", price: 1750000, rating: "4.6", reviews: "54", image: "https://images.pexels.com/photos/33587697/pexels-photo-33587697.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rak Buku", room: "storage", material: "Kayu pinus solid, palang baja", dimensions: "Lebar 55 cm × Dalam 35 cm × Tinggi 190 cm", description: "Rak buku bersandar dengan lima tingkat yang mengecil ke atas dan disandarkan ke dinding." },
  { id: "bookshelf-dewi-cube", name: "Dewi Rak Buku Kubus", price: 990000, oldPrice: 1190000, discount: "17%", rating: "4.7", reviews: "112", image: "https://images.pexels.com/photos/19582451/pexels-photo-19582451.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rak Buku", room: "storage", material: "Kayu olahan, laminasi motif kayu", dimensions: "Lebar 90 cm × Dalam 30 cm × Tinggi 90 cm", description: "Rak kisi kubus dengan enam kompartemen terbuka, cocok untuk piringan vinyl, keranjang, dan kotak display." },
  { id: "bookshelf-agung-tall", name: "Agung Rak Perpustakaan Tinggi", price: 3790000, rating: "4.8", reviews: "66", image: "https://images.pexels.com/photos/32583822/pexels-photo-32583822.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Rak Buku", room: "storage", material: "Veneer oak, badan kayu olahan, rangka baja", dimensions: "Lebar 100 cm × Dalam 32 cm × Tinggi 200 cm", description: "Rak perpustakaan tinggi enam tingkat dengan alas tertutup dan pengait dinding agar stabil di ruang keluarga." },
  { id: "rug-sora-160x230", name: "Sora Karpet Tenun Datar", price: 1890000, rating: "4.7", reviews: "143", image: "https://images.pexels.com/photos/7587828/pexels-photo-7587828.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Karpet", room: "living", material: "Tenun datar polipropilena, lapisan bawah lateks anti-slip", dimensions: "Lebar 160 cm × Panjang 230 cm", description: "Karpet tenun datar dengan motif geometris lembut, cukup rendah untuk diletakkan di bawah meja makan tanpa mengganggu kursi." },
  { id: "rug-bumi-120x170", name: "Bumi Karpet Tufted", price: 890000, rating: "4.5", reviews: "62", image: "https://images.pexels.com/photos/16820353/pexels-photo-16820353.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Karpet", room: "living", material: "Bulu tufted campuran katun, lapisan bawah kanvas katun", dimensions: "Lebar 120 cm × Panjang 170 cm", description: "Karpet tufted kecil dengan tepi bermotif halus, ukurannya pas untuk samping tempat tidur atau ujung sofa." },
  { id: "rug-aulia-200x290", name: "Aulia Karpet Motif Klasik", price: 3490000, rating: "4.8", reviews: "108", image: "https://images.pexels.com/photos/32025734/pexels-photo-32025734.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Karpet", room: "living", material: "Bulu pendek poliester, lapisan bawah lateks anti-slip", dimensions: "Lebar 200 cm × Panjang 290 cm", description: "Karpet besar berbulu pendek dengan motif klasik yang pudar, cocok menjadi penyeimbang seluruh area duduk ruang tamu." },
  { id: "rug-jaya-160x230", name: "Jaya Karpet Wool Heathered", price: 2490000, rating: "4.6", reviews: "77", image: "https://images.pexels.com/photos/7417505/pexels-photo-7417505.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Karpet", room: "living", material: "Bulu campuran wool, lapisan bawah kanvas katun", dimensions: "Lebar 160 cm × Panjang 230 cm", description: "Karpet campuran wool bertekstur dengan warna abu heathered yang menyamarkan noda harian di ruangan ramai." },
  { id: "rug-rani-120x170", name: "Rani Karpet Garis Tenun", price: 750000, oldPrice: 950000, discount: "21%", rating: "4.6", reviews: "129", image: "https://images.pexels.com/photos/37305984/pexels-photo-37305984.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Karpet", room: "living", material: "Katun tenun, lapisan bawah titik PVC anti-slip", dimensions: "Lebar 120 cm × Panjang 170 cm", description: "Karpet katun yang bisa dicuci dengan garis tenun, ringan sehingga mudah dipindah dan dibersihkan setelah tumpah." },
  { id: "mirror-vera-round", name: "Vera Cermin Dinding Bulat", price: 690000, rating: "4.7", reviews: "88", image: "https://images.pexels.com/photos/7319683/pexels-photo-7319683.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Cermin", room: "bedroom", material: "Bingkai baja powder coating, kaca cermin silver", dimensions: "Diameter 60 cm × Kedalaman 3 cm", description: "Cermin dinding bulat dengan bingkai metal tipis, bisa digantung datar atau disandarkan di rak atas konsol." },
  { id: "mirror-aluna-arch", name: "Aluna Cermin Lantai Lengkung", price: 2190000, rating: "4.8", reviews: "121", image: "https://images.pexels.com/photos/15269290/pexels-photo-15269290.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Cermin", room: "bedroom", material: "Bingkai kayu karet solid, kaca cermin silver", dimensions: "Lebar 60 cm × Tinggi 170 cm", description: "Cermin lantai melengkung dengan bingkai ramping, cukup tinggi untuk melihat seluruh pakaian di samping lemari." },
  { id: "mirror-kira-square", name: "Kira Cermin Dinding Persegi", price: 480000, rating: "4.5", reviews: "41", image: "https://images.pexels.com/photos/7598131/pexels-photo-7598131.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Cermin", room: "bedroom", material: "Bingkai kayu olahan, kaca cermin bevel", dimensions: "Lebar 50 cm × Tinggi 50 cm", description: "Cermin dinding persegi dengan tepi bevel dan braket tersembunyi, ukurannya pas untuk kamar mandi kecil atau lorong." },
  { id: "mirror-sena-full", name: "Sena Cermin Panjang Penuh", price: 1650000, rating: "4.6", reviews: "57", image: "https://images.pexels.com/photos/7318661/pexels-photo-7318661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Cermin", room: "bedroom", material: "Bingkai kayu oak solid, kaca cermin silver", dimensions: "Lebar 55 cm × Tinggi 165 cm", description: "Cermin persegi panjang sepanjang badan yang disandarkan ke dinding, dengan bingkai kayu dan sedikit kemiringan ke belakang." },
  { id: "mirror-nila-octagon", name: "Nila Cermin Segi Delapan", price: 890000, rating: "4.7", reviews: "73", image: "https://images.pexels.com/photos/14870469/pexels-photo-14870469.jpeg?auto=compress&cs=tinysrgb&h=650&w=940", category: "Cermin", room: "bedroom", material: "Bingkai kayu solid, kaca cermin silver", dimensions: "Diameter 70 cm × Kedalaman 3 cm", description: "Cermin bersisi delapan dengan bingkai kayu lebar, dirancang sebagai pusat perhatian di atas meja rias atau meja masuk." },
];

export const rupiah = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);
export const getProduct = (id: string) => products.find((product) => product.id === id);
export const getCategory = (slug: string) => categories.find((category) => category.slug === slug);

/**
 * Related products must stay within the SAME product category (e.g. Sofa -> Sofa,
 * Meja Kerja -> Meja Kerja), not merely the same room. A room like "Ruang Tamu" holds
 * multiple unrelated categories (Sofa, Kursi Santai, Meja Tamu), so filtering by room
 * alone surfaced unrelated items on the product detail page. Category match first;
 * fall back to same-room only if the category genuinely has no other members yet.
 */
export const relatedProducts = (product: Product) => {
  const sameCategory = products.filter((item) => item.category === product.category && item.id !== product.id);
  if (sameCategory.length > 0) return sameCategory.slice(0, 4);
  return products.filter((item) => item.room === product.room && item.id !== product.id).slice(0, 4);
};
